name: vulnerability-scan
on: [push, workflow_dispatch]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: lacework/lw-scanner-action@v1.2.0
        name: Scan container image for vulnerabitilies using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: techallylw/vulnerable-container
          IMAGE_TAG: v0.0.1
          SAVE_RESULTS_IN_LACEWORK: true
