FROM nginxinc/nginx-unprivileged:1.23.1

USER root

RUN apt-get update && apt-get install -y sudo && \
    usermod -aG sudo $(id -nu 101) && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER 101